### PR TITLE
Add new `dblink` option for foreign tables and for IMPORT FOREIGN SCHEMA.

### PR DESCRIPTION
**Pull request by nboullis**
I tried to scratch my own itch (see issue #356).

Comments are welcome.

### CODE REVIEW

**Comment by laurenz** [comment]
Thanks for your effort!

I have given the code a quick look, and it looks in fairly good shape. The code in `oracleGetImportColumn` isn't really pretty, maybe I can find something that pleases my sense of beauty better. I'll see what I can come up with.

I found an obvious bug while testing, for which I have sent a pull request to your fork.

I tried to test `IMPORT FOREIGN SCHEMA` with a simple use case, and it worked.

The bug I found caused warnings and errors on my end because I built with `--enable-cassert`. Maybe you can build PostgreSQL with that option and try to test it some more &ndash; two testers find more than one.

**Comment by nboullis** [comment]
Thanks for your feedback.

Thanks also for pointing that bug; I feel ashamed for it.

I might try yo build PostgreSQL with `--enable-cassert` but I never tried to build PostgreSQL myself (I’ve always been using binary packages from the Debian repositories).  It will also require to build a real test setup. (I’ve currently been using a production server, only on a separate cluster…)

**Comment by nboullis** [comment]
Oh. I forgot to mention that, although we may have different sense of beauty, I also think the code I added in `oracleGetImportColumn` is ugly… But that still was the “best” way I found to implement the feature without being too intrusive in your code…

**Comment by laurenz** [comment]
I couldn't help tinkering with the patch a little, I am happy with it as it is.

Thanks again!

**Pull request merged**
