### PR TITLE
Add paths for Oracle 21.1 and 19.10 to Makefile

### PR DESCRIPTION
**Pull request by ivanlonel**
64-bit versions only, as there is nothing past 19.9 in the official download page for Linux 32-bit as of this commit:
https://www.oracle.com/database/technologies/instant-client/linux-x86-32-downloads.html

### CODE REVIEW

**Comment by laurenz** [comment]
Thanks!
I wonder about Oracle 21: I couldn't find an Instant Client download for that version, and the path you use is surprisingly different from older versions. Can you tell me more about that?
Did you omit the paths for the 32-bit client on purpose?

**Comment by laurenz** [comment]
If you didn't find the software on the Instant Client download page, from where did you get it?

**Comment by ivanlonel** [comment]
I didn't find the 32-bit one. The 64-bit instant client can be downloaded from the (separate) [Linux 64-bit official downloads page](https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html).

I found it weird that they dropped the minor version from the path as well, but we can verify it's correct by inspecting the [SDK RPM file](https://download.oracle.com/otn_software/linux/instantclient/211000/oracle-instantclient-devel-21.1.0.0.0-1.x86_64.rpm).

**Comment by laurenz** [comment]
Ah, OK, thanks for double-checking and for the patch!

**Pull request merged**
