### PR TITLE
NULL and empty array/list fixes

### PR DESCRIPTION
**Pull request by dreckard**
*Fixed crash with WHERE <col> = ANY(NULL)
Translate empty arrays into NULL to provide expected results*

I discovered a null pointer crash when trying to run a query with `WHERE <col> = ANY(NULL)`.  That's a fairly useless condition equivalent to 0=1 but I had some dynamic SQL generating it and knocking my server offline.  Since it's valid for Oracle too I see no reason not to pass it on in the Oracle query.

I also modified the empty array behavior from just ignoring the condition to using NULL. This gives you an empty result set of course, same as pure Postgre. Dropping the condition as before seems to cause the FDW API to do weird things in some cases too, like ignore a LIMIT clause and keep calling IterateForeignScan().

### CODE REVIEW

**Comment by laurenz** [comment]
Thank you for the patch!  I can easily reproduce the crasher.

Can you explain the problem with empty arrays in my code?
Can you give me an example where a query with an empty array behaves wrong?

Yours,
Laurenz Albe

**Comment by dreckard** [comment]
Sure no problem, glad to be of help!

My mistake on the empty arrays, I misunderstood the effect of the code [there](https://github.com/laurenz/oracle_fdw/pull/23/files#diff-72b991171844f1b822159147a3579f62L2636).  There is no accuracy problem with the current code, and now I understand what was going on with the FDW calls from Postgre.  So the current behavior is that using an empty array becomes a Postgre filter condition instead of being pushed down, correct?  No fear of inaccurate results then, just performance.

The only problem I see now with pushing down every empty array as NULL is that Oracle and Postgre differ on what to return with `NOT IN ('{}')`/`NOT IN ('')`.  Oracle returns nothing and Postgre returns everything.  My patch might need a little extra logic to handle that and keep things faithful to Postgre.

**Comment by laurenz** [comment]
I understand, thanks for the explanation.

Since the query runs in PostgreSQL, it must follow PostgreSQL semantics. So the current behaviour is OK. I'll merge your patch and rip out the part that handles empty arrays.

**Comment by dreckard** [comment]
Sounds good, thanks!

**Pull request merged**
